### ISSUE TITLE
API Problems

### ISSUE THREAD

**Issue by ExampleGaming702** [ethanent/hypixel-api#2]
I dont understsand what Ethanent means... Could someone explain this to me please?
And I also get the error Message: Malformed UUID... Please help if u know what the problem is.

Thank you!

**Comment by notWolfxd** [comment]
How are you formatting your query? Maybe put a few lines of your code, because afaik everything works just fine from my testing.

'Ethanent' is the IGN of the person who created this, if you're going off the example, you would replace that with the IGN of the person you're trying to fetch.

**Comment by CocoaCrispies** [comment]
Ok, so what does the 'name' argument do?

**Comment by ethanent** [comment]
Hello, @CocoaCrispies. The selector type argument, which should either be `"name"` or `"uuid"`, is used to specify the type of selector which will be passed as the second argument. If you provide `"name"`, hypixel-api will attempt to resolve the provided name to a UUID before making the query to Hypixel API, as the API deprecated requests by name.
