### ISSUE TITLE
[Question/Problem] Get User Data

### ISSUE THREAD

**Issue by Skeec54** [ethanent/hypixel-api#6]
Hello,

I currently have programmed a bot that he checks a member if he has ... skill req but the problem is i get this file as output (https://hastebin.com/ipedawihoz.json) and i don't know how i get now on the other side of the member with the "uuid" anyone could help me?

**Comment by Mujaca** [comment]
I used another API (https://playerdb.co/api/player/minecraft/${UUID}) to reverse back from UUID to player Name.
The Code I wrote for this is as follow : 
`
var request = require('request');

async function getPlayerName(UUID) {
    return new Promise(async resolve => {
        request(`https://playerdb.co/api/player/minecraft/${UUID}`, function (error, response, body) {
        resolve(JSON.parse(body).data.player.username);
    });
});
}`

**Comment by notWolfxd** [comment]
So if you're looking to get the member's stats after the "members" part I would recommend something like such:

const membersObj = members;
const getFirstMember = Object.keys(membersObj)[0];

Then you should be able to do something along the lines of:

const memberFirstJoin = getFirstMember.first_join;
// Returns: 1591208618520 
const memberLogObjective = getFirstMember.objectives.collect_log.status;
// Returns: COMPLETE

You can replace the '0' in the getFirstMembers constant to any number. 0 represents the first member in your link, 1 would represent the second. Basically whatever number in your link the member is - 1.

**Comment by Skeec54** [comment]
Ok thanks for the help :D
