### ISSUE TITLE
API ERROR

### ISSUE THREAD

**Issue by Fwwyn** [ethanent/hypixel-api#9]
Hi,
Im building a discord bot for hypixel using your api and I tried using the "Getting Player Information" Feature but when I tried running it i get the error, " Invalid API key". 
I used the exact code as shown on NPM (https://www.npmjs.com/package/hypixel-api)
"const HypixelAPI = require('hypixel-api')
 
const client = new HypixelAPI('API-key')
 
client.getPlayer('name', 'Ethanent').then((player) => {
    console.log(player)
}).catch((err) => {
    console.error('Error! ' + err)
})"

If you could help me fix this that would be great,

thanks in advance

**Comment by Fwwyn** [comment]
Nevermind I fixed it

**Comment by Skeec54** [comment]
Hi, 

did you replaced the `new HypixelAPI('API-key')` With your api key?

**Comment by Skeec54** [comment]
i think this can be closed.
